### ISSUE TITLE
No issue... Just some questions.

### ISSUE THREAD

**Issue by rathaROG** [eren-ck/st_dbscan#1]
Does it work on more dimension data like 3D (x,y,z)? I tested with 3D data and everything seemed to be fine. I just want you to clarify. 

By the way, I've been looking for C++ of ST-DBSCAN as well but no luck. Do you have any idea for C++ version?

**Comment by eren-ck** [comment]
Yes the package works also for datasets with more than two dimensions. So also for 3D data. 
I am not aware of any particular ST-DBSCAN implementation for C++. 

I you have further questions please reopen the issue.
