### ISSUE TITLE
Provide time series before the spatial attributes

### ISSUE THREAD

**Issue by rtrepos** [eren-ck/st_dbscan#10]
First, thanks for this implementation of this clustering method.
I was trying to use it with spatial attributes (x,y) and for each location I have a time series (and not only one value).
I understood from the paper that it was possible

But from the demo and the comment here
https://github.com/eren-ck/st_dbscan/blob/ace025a684edca57fd1fc765e7bda14cd0fb3c6a/src/st_dbscan/st_dbscan.py#L75.
I understand that only 1 value can be provided as temporal feature (and not a complete time series). Am I wrong ?
Thanks again
Ronan

**Comment by eren-ck** [comment]
Hello Ronan, 
I am not sure if I understand the questions correctly. But yes only providing one values so (x) is also sufficient. 

Cheers, 
Eren
