### ISSUE TITLE
Units or metrics

### ISSUE THREAD

**Issue by nikhil-pillai** [eren-ck/st_dbscan#11]
What would be the units of these values in eps1 = 0.05, eps2 = 10. Are they m/km or s/min

**Comment by nikhil-pillai** [comment]
Does this repo only supports metric in cartesian coordinates ? Are there any extension to haversine to cluster lat lon.

**Comment by eren-ck** [comment]
Hello, 
the eps1 defines the epsilon distance, ideally for a normalized or standardized dataset. Thus, it is not in m or km. Please refer to detailed descriptions of epsilon for [DBSCAN](https://en.wikipedia.org/wiki/DBSCAN).  

The second eps2 distance defines the temporal distance between two time steps. Please refer to the following paper for more details [Peca et al.](http://geoanalytics.net/and/papers/eurova12.pdf). 

The package only supports cartesian coordinates, so you would have to project the geographic data to a 2D space, for example, with [Equirectangular projection](https://en.wikipedia.org/wiki/Equirectangular_projection).

Cheers, 
Eren
