### ISSUE TITLE
ValueError: frame_size, frame_overlap not correctly configured

### ISSUE THREAD

**Issue by apiszcz** [eren-ck/st_dbscan#4]
I tested 10000 records of random data with frame_size = 50

```
    138         if not frame_size > 0.0 or not frame_overlap > 0.0 or frame_size < frame_overlap:
    139             raise ValueError(
--> 140                 'frame_size, frame_overlap not correctly configured.')
    141 
    142         # unique time points

ValueError: frame_size, frame_overlap not correctly configured.
```

**Comment by eren-ck** [comment]
Could you please tell me what parameters you used to call the method?

**Comment by apiszcz** [comment]
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from st_dbscan import ST_DBSCAN
```


```python
# create a 3d data set, e,x,y
df=pd.DataFrame(np.random.random((100000,3)),columns=['e','x','y'])
df=df.sort_values('e')
df.e = (df.e * 86400)+86400
```


```python
# normalize the data 
df['x'] = (df['x'] - df['x'].min()) / (df['x'].max() - df['x'].min())
df['y'] = (df['y'] - df['y'].min()) / (df['y'].max() - df['y'].min())
# transform to numpy array
data = df.loc[:, ['e','x','y']].values
```


```python
%%time
st_dbscan.fit_frame_split(data, frame_size = 50)
```


    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <timed eval> in <module>
    

    C:\p\via37\lib\lib\site-packages\st_dbscan\st_dbscan.py in fit_frame_split(self, X, frame_size, frame_overlap)
        138         if not frame_size > 0.0 or not frame_overlap > 0.0 or frame_size < frame_overlap:
        139             raise ValueError(
    --> 140                 'frame_size, frame_overlap not correctly configured.')
        141 
        142         # unique time points
    

    ValueError: frame_size, frame_overlap not correctly configured.

**Comment by eren-ck** [comment]
Can you tell me which version of st_dbscan you are using? I cannot replicate the error. See the screenshot below.  

![Screen Shot 2020-12-09 at 09 01 24](https://user-images.githubusercontent.com/22754816/101601889-7fe2a100-39fd-11eb-8e11-0d32d12435a1.png)

**Comment by apiszcz** [comment]
0.1.5
Can you place %%time on the first line in cell 4, i'm interested to learn how long this takes. Thank you.

**Comment by eren-ck** [comment]
See below - hope this helps you. 
```
CPU times: user 8.61 s, sys: 118 ms, total: 8.72 s
Wall time: 8.83 s
<st_dbscan.st_dbscan.ST_DBSCAN at 0x7fdd5944a310>
```

**Comment by eren-ck** [comment]
Does this resolve the issue for you?
