### ISSUE TITLE
density factor implementation

### ISSUE THREAD

**Issue by priamai** [eren-ck/st_dbscan#6]
Hi there,
I was reading the original paper and your implementation and correct if I am wrong but there is no provision for the density factor thus there will be issues identifying adjacent clusters.
Unless this is implemented in the standard DBSCAN algorithm in SKLEARN but I can't find any info in there either.

**Comment by eren-ck** [comment]
Hello, 
yes, the density factor as described in the paper [1] is currently not implemented.  However, we assume that if you use the `fit_frame_split` as described in the paper [2], that to some degree different densities over time will also be supported. However, not within the same partitioned frame. A potential solution for this is to simply replace the algorithm in a fork with the HDBSCAN algorithm ([link](https://github.com/scikit-learn-contrib/hdbscan)) which is able to capture different densities. 

I hope this helps you.  

Cheers, 
Eren

1. Birant, Derya, and Alp Kut. "ST-DBSCAN: An algorithm for clustering spatial–temporal data." Data & Knowledge Engineering 60.1 (2007): 208-221.
2. Peca, I., Fuchs, G., Vrotsou, K., Andrienko, N. V., & Andrienko, G. L. (2012). Scalable Cluster Analysis of Spatial Events. In EuroVA@ EuroVis.

**Comment by priamai** [comment]
Awesome thanks for the pointers, I am reading them.
