### ISSUE TITLE
wrong when use "st_dbscan.fit_frame_split"

### ISSUE THREAD

**Issue by fff2zrx** [eren-ck/st_dbscan#7]
hello,eren-ck!
when I use "st_dbscan.fit_frame_split", I set 
`st_dbscan.fit_frame_split(data, frame_size = 500)`
sometimes it goes well,sometimes it goes wrong:
**the length of labels don't equal the length of data**
how should  I solve this question? Thank you!

**Comment by eren-ck** [comment]
Hello, 
do you have a dataset or example with which I can reproduce the issue?  

Cheers, 
Eren
